# Generated by Django 4.2.2 on 2023-06-10 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_customerprofile_image_url_alter_customerprofile_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='image_url',
            field=models.ImageField(blank=True, default='media/images.png', null=True, upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
