# Generated by Django 4.2.2 on 2023-06-10 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_customerprofile_image_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerprofile',
            options={'verbose_name': 'Профиль покупателя', 'verbose_name_plural': 'Профили покупателя'},
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='city',
            field=models.CharField(default=None, max_length=250, null=True),
        ),
    ]
