# Generated by Django 4.2.2 on 2023-07-17 02:42

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_customerprofile_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='on_mail_listing',
            field=models.BooleanField(default=False, verbose_name='Подписан на почтовую рассылку'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Эл. Почта'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, validators=[django.core.validators.RegexValidator('^((8|\\+7)[\\- ]?)?(\\(?\\d{3}\\)?[\\- ]?)?[\\d\\- ]{7,10}$')], verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='user_name',
            field=models.CharField(max_length=150, unique=True, verbose_name='Имя пользователя'),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='city',
            field=models.CharField(default=None, max_length=250, null=True, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL, verbose_name='Покупатель'),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='image_url',
            field=models.ImageField(blank=True, default='media/images.png', null=True, upload_to='uploads/%Y/%m/%d/', verbose_name='Аватар'),
        ),
    ]
