# Generated by Django 4.2.2 on 2023-06-18 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_product_discount_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image_url',
            field=models.ImageField(blank=True, default='media/images.png', null=True, upload_to='products/uploads/%Y/%m/%d/'),
        ),
    ]
