# Generated by Django 4.2.2 on 2023-06-19 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_alter_product_discount_percent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='image_url',
            new_name='image',
        ),
    ]
