# Generated by Django 4.2.2 on 2023-06-19 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_rename_image_url_productimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='image',
        ),
        migrations.AddField(
            model_name='productimage',
            name='image_url',
            field=models.ImageField(blank=True, default='media/images.png', null=True, upload_to='products/uploads/%Y/%m/%d/', verbose_name='Изображение'),
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ManyToManyField(default=1, to='store.productimage', verbose_name='Изображение'),
        ),
    ]
