# Generated by Django 4.2.2 on 2023-06-19 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_remove_productimage_image_productimage_image_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='image_url',
            new_name='image',
        ),
    ]
