# Generated by Django 4.2.2 on 2023-06-21 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_alter_productimage_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='image_url',
            new_name='image',
        ),
    ]
