# Generated by Django 4.2.2 on 2023-06-30 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_category_is_parent_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='Изображение'),
        ),
    ]
