# Generated by Django 4.2.2 on 2023-07-17 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_alter_productimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='send_email_created',
            field=models.BooleanField(default=False),
        ),
    ]
