services:
  web:
    build: .
    volumes:
      - .:/store
      - static_volume:/store/static
      - media_volume:/store/media
    ports:
      - 8000:8000
    env_file:
      - web.env
    image: app:django
    container_name: django_store_api
    command: python manage.py runserver 0.0.0.0:8000


  db:
    image: postgres:14.1-alpine
    restart: always
    env_file:
      - web.env
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local

  static_volume:
  media_volume:
