# Generated by Django 4.2.2 on 2023-07-03 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0022_alter_productimage_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Рейтинг')),
                ('usage_period', models.CharField(choices=[('LESS THAN MONTH', 'Меньше месяца'), ('MONTH_TO_YEAR_HALF', 'От месяца до полугода'), ('YEAR_HALF_TO_ONE_YEAR', 'От полугода до года'), ('ONE_YEAR_MORE', 'Более одного года')], max_length=255, verbose_name='Срок использования')),
                ('advantages', models.TextField(verbose_name='Преимущества')),
                ('disadvantages', models.TextField(verbose_name='Недостатки')),
                ('comment', models.TextField(verbose_name='Комментарий')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['-created'],
            },
        ),
    ]
