# Generated by Django 4.2.2 on 2023-07-03 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_productreview_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productreview',
            old_name='product',
            new_name='product_id',
        ),
    ]
